pom.xml
I tested the changes on the Vitruv project.
Note: I head to run maven with `-U` once because it wouldn’t find some dependency otherwise.
=> Update to Eclipse 2020-06

pom.xml
I tried the parent with Vitruv. The only issue was that `org.eclipse.emf.emfstore.common` is not present in 2020-12 anymore. However, we don’t seem to actually use it, at least I got no errors after simply removing the dependency, so… ¯\_(ツ)_/¯
=> Update to Eclipse 2020-12

pom.xml
- Remove the obsolete `maven-compiler-plugin`
- Separate MWE2 workflows into cleanup and generation
- Activate MWE2 workflows by convention (workflow files at specific locations) instead of marker files with configuration properties
- Activate aggregated updatesite build by aggregation file rather than additional marker file
- Remove Eclipse updates repository
=> Profile Reconfiguration

pom.xml
Marker file | result
--- | ---
_none_ | same as previously: run in an Equinox platform, but without a workbench
`.tests-without-platform` | run with `maven-surefire`
`.tests-need-workbench | run in an Equinox platform _with_ a workbench
=> Allow Test Projects to Configure Their Test Harness With Marker Files

pom.xml
* Sets the test output directory for tests run with `maven-surefire` to the output directory defined for the project instead of a hardcoded folder
* Corrects the ID of the `tycho-p2-plugin`
=> Tests and P2 Metadata Plugin Correction

.github/workflows/ci.yml, README.md, pom.xml
This PR adds a GitHub actions configuration that
- verifies every commit with Maven
- deploys snapshot version commits to the `master` branch to the Sonatype snapshots repository
- performs a release for release version commits that are tagged as a release to the Sonatype release repository
=> GitHub Actions Verification and Deployment 

pom.xml
Configure mvn and tycho surefire plugins to show the full stack traces for any test error.
=> Show full stack trace on test error

README.md, pom.xml
Several upgrades in relation to moving to Eclipse 2021-12:
* Change updatesites from http to https
* Change Eclipse updatesite to 2021-12
* Upgrade to Tycho 2.5.0, JUnit 5.8.2
* Add functionality for automatic adjustment of workspace paths within MWE2 workflow to be executable in both Eclipse and the Maven build
=> Eclipse 2021-12

.gitignore, .mvn/jvm.config, formatter.xml, pom.xml, spotless.importorder
This is an initial PR to support formatting/code style with spotless thus addressing vitruv-tools/Vitruv#495 and vitruv-tools/Vitruv#497. It allows to check these guidelines via `mvn spotless:check` and apply them automatically with `mvn spotless:apply`.
- An initial Eclipse-based formatting configuration
- A spotless configuration as part of the parent pom
- e.g. line width/comment line width
- Apply spotless in a big-bang manner to the repos
- Add Github Action workflows for `spotless:check` to the repos
**EDIT:** Note that this PR does not yet include workflows to run spotless checks on incoming PRs. Thus, we can merge this PR and then add the missing workflows whenever we want to start enforcing these style guidelines.
=> Enforce formatting with spotless

.github/workflows/ci.yml, README.md
This PR changes the release deployment behaviour to rely on GitHub Releases instead of on Git tags. In particular, a release version is only deployed after a GitHub release is created.
It would be beneficial to also test that the trigger correctly works for Releases. Following GitHub documentation, Release can be deleted again, thus we could create a test release for this purpose. However, this would require actually pushing something to Maven Central. Open for suggestions how to circumvent this and still being able to test the workflow.
=> Deploy release versions after creating a GitHub Release

.github/workflows/ci.yml, README.md, pom.xml
This PR prepares the repository for renaming the default branch from `master` to `main`.
This follows general naming conventions adopted by major GIT hosters and is already done in the recently created Vitruv repositories (DSLs / Change / Aggregated-Update-Site).
GitHub provides [built-in functionality](https://github.com/github/renaming#renaming-existing-branches) for renaming the branch. This PR adjusts the CI actions, build artifacts, and the Readme. Thus, first the branch has to be renamed, then the PR should be merged.
As we use static versions of the build parent in all Vitruv repositories, this change should not have any effect on other repositories.
=> Rename branch `master` to `main`

pom.xml
Replaces the developer entry in the POM with a generic developer based on a mailing list.
=> Set generic developer based on mailing list as correspondence in pom

.github/PULL_REQUEST_TEMPLATE/major.yaml, .github/PULL_REQUEST_TEMPLATE/minor.yaml, .github/workflows/ci.yml, README.md, pom.xml
As discussed in a recent developers meeting, we will change the current branch structure of one `main` branch into which all changes are merged. The main motivation for this is the complexity when trying to add a minor release while already changes for a major release were deployed to `main`.
The new branching approach will use the two primary branches `main` and `develop`. `develop` contains major releases which are not released immediately. Snapshot builds are thus created on the `develop` branch. Any release must be based on the `main` branch.
This adjustment will require developers to select the appropriate branch to merge into when creating pull requests. Minor changes shall immediately be merged into `main`, major changes into `develop`.
Maybe GitHub even provides some functionality …
=> Prepare CI for new branch management regarding releases

.github/pull_request_template.md
Fixes some misconception regarding semantic versioning in the PR template description.
Now the branching behaviour is described as follows:
- Major (x.\_.\_) -> develop
- Minor (\_.x.\_) -> develop
- Patch (\_.\_.x) -> main
=> Correct update names regarding semantic versioning

pom.xml
Eclipse 2022-06 uses JUnit 5.8.1, but we have improved to 5.9.0 before. Since the minor version increment, of course, is API breaking, we need to revert to 5.8.1.
This is patch, thus merged against `main` and released as `2.0.1`.
=> Adapt JUnit version for Eclipse 2022-06

.github/workflows/ci.yml
In preparation for migrating to Java 17, this PR already updates the CI to use Java 17 for building in source compatibility mode for Java 11 (as specified in [Maven Build Parent](https://github.com/vitruv-tools/Maven-Build-Parent)).
Additionally, the Java distribution is changed to the Eclipse distribution temurin.
=> Migrate to Java 17 CI actions

.github/workflows/ci.yml
Currently, PRs from external contributors will fail (like the DependaBot PRs) as the configuration verification requires the secret GPG key. Thus, this PR disables GPG signing for verification builds. Any release-related job still uses GPG signing.
=> Skip gpg signing for verifying the configuration

pom.xml
- Updates the Eclipse version to 2022-12
- Updates Java to Java 17
- Updates dependencies
- Added the Eclipse Orbit Update Site as some dependencies (like Junit Jupiter) are not shipped by default with the Eclipse distribution anymore.
After this PR I would suggest to release a new version such that we can migrate all depending projects to Java 17 (which I already prepared). There is one API-breaking change coming from the minor increment of the Junit Jupiter version (thus with correct semantic versioning it must not exist) but from our own API there is nothing API-breaking. Thus, I would suggest version **2.1.0** instead of **3.0.0**. Opinions?
=> Eclipse 2022-12

pom.xml
Updates the dependencies such that Maven 3.9.0 can be supported.
Updates Eclipse to 2023-03. 
Updates the version number to 2.1.2
Fixes #62
=> Add support for Maven 3.9.1 and Eclipse 2023-03

pom.xml
Updates the following plugin dependencies:
- org.eclipse.emf.codegen.ecore: 2.41.0 -> 2.42.0
- org.eclipse.emf.mwe.utils: 1.15.0 -> 1.16.0
- org.eclipse.emf.mwe2.launch: 2.21.0 -> 2.22.0
- org.eclipse.emf.mwe2.lib: 2.21.0 -> 2.22.0
- org.eclipse.xtext.common.types: 2.38.0 -> 2.39.0
- org.eclipse.xtext.xtext.generator: 2.38.0 -> 2.39.0
- org.eclipse.xtext.xtext-maven-plugin: 2.38.0 -> 2.39.0
- org.eclipse.xtend.core: 2.38.0 -> 2.39.0
- org.eclipse.xtend.xtend-maven-plugin: 2.38.0 -> 2.39.0
Also adds org.eclipse.emf.common:2.42.0 as explicit dependency of the `exec-maven-plugin` and `xtend-maven-plugin` plug-ins.
This was done to resolve build problems due to outdated versions of emf.common that these plug-ins tried to use.
=> Update EMF, Xtext, Xtend dependencies
