pom.xml
- Set Eclipse 2020-12 for updatesite aggregation
- Disable project-specific settings for Tycho compiler per default
=> Project-specific settings

pom.xml
… and replace the deprecated `tycho-source-feature-plugin` with `tycho-source-plugin`.
=> Update to Tycho 2.2

pom.xml
Keeps the logs clean and readable
=> Mute Tests

pom.xml
Released minor bugixes (plugin ID) and improvements (pipe logging to file, generalize test output folder definition) as 1.1.1.
=> Release 1.1.1

README.md, pom.xml
Improves dependencies for Eclipse 2021-03.
Updates and corrects documentation in the readme.
=> Eclipse 2021-03

pom.xml
Improves dependencies for Eclipse 2021-06.
=> Eclipse 2021-06

pom.xml
Releases POM version 1.3.0 with Eclipse dependencies increased to 2021-06.
=> Release 1.3.0

.github/CODEOWNERS
Configures the code owners.
@tsaglam @TomWerm any of you wants to be code owner too?
=> Specify Codeowners

.github/PULL_REQUEST_TEMPLATE/major.md, .github/PULL_REQUEST_TEMPLATE/major.yaml, .github/PULL_REQUEST_TEMPLATE/minor.md, .github/PULL_REQUEST_TEMPLATE/minor.yaml
This PR aims at fixing the PR templates.
=> Fixes the pull request templates

pom.xml
=> Integrate patch commits

pom.xml
=> Update version to 2.1.0-SNAPSHOT

pom.xml
Closes https://github.com/vitruv-tools/Vitruv-DSLs/issues/17
=> Support aarch mac

README.md
+ ci status
+ issues
+ license
=> display latest release in Readme

.github/dependabot.yml
=> setup dependabot for GitHub actions

.github/workflows/ci.yml
=> Fix CI caching

pom.xml
=> [Release Process] 2.2.0-SNAPSHOT

.github/workflows/ci.yml, pom.xml
- Updates the tycho version to 3.0.1 to re-enable update site generation
- Adds properties for SDQ repository versions
- Changes release process from separate stage and deploy to direct deployment (as steps are unconditionally executed after another anyways)
Prepares release 2.1.1
=> Release 2.1.1

.github/workflows/ci.yml, pom.xml
=> Merge 2.1.1 into develop

pom.xml
=> Update SDQ commons dependency to 2.2.0

.github/workflows/ci.yml, .gitignore, .mvn/wrapper/maven-wrapper.properties, mvnw, mvnw.cmd, pom.xml
requires Maven version > 3.9.0
=> update Tycho to fix "Unresolved requirement" error

pom.xml
should fix our current build problems
=> Increase Tycho Version

pom.xml
see https://github.com/sonatype/nexus-public/issues/110#issuecomment-2129162469
=> fix release staging

.github/workflows/release.yml, pom.xml
explicit release does not seem to work (see #96 and #94)
=> Use auto release instead of explicit release

pom.xml
- source plugin
- javadoc plugin
- code coverage plugin
- *small fix*
=> Add missing parts to the build process
